### ISSUE TITLE
Change CMD to ENTRYPOINT

### ISSUE THREAD

**Issue by lwolfsonkin** [corprew/syntaxnet-conll-docker#1]
This is mostly a suggestion. You have that `--conll` flag in your script, but if I correctly understand how `docker` works, there is no _nice way_ to access it without replacing that command with itself followed by `--conll`. I think it would be cleaner if you changed

```
CMD ["bash", "/root/models/syntaxnet/demo-emits-conll.sh"]
```

to

```
ENTRYPOINT ["bash", "/root/models/syntaxnet/demo-emits-conll.sh"]
```

Then, one could run 

```bash
docker run --rm -i corprew/syntaxnet-conll < input.txt
```

for normal text input and

```bash
docker run --rm -i corprew/syntaxnet-conll --conll < input.txt
```

for conll input

**Comment by corprew** [comment]
Hey -- 

that's a great suggestion.  If I ever make this a general purpose, I'll do that.  As it is, this mostly exists to serve as a drop in replacement for something that didn't have this dockerized, so this works fairly well.  

Let me know if you decide to fork it and have it work like that and i'll provide a pointer to your repo. 

Thanks,  

--Corprew
